[package]
name = "ggj19"
version = "0.1.0"
authors = ["Andreas Neukoetter <andreas@omni-mad.com>"]
edition = "2018"

[dependencies]
minifb = "*"
image = "0.21.0"
rand = "0.6.4"
perlin_noise = "1.0.1"
